import type {
  FullWorkflowEdge,
  FullWorkflowNode,
} from '@/components/agents/types'

export type AgentKey =
  | 'plan'
  | 'procurement'
  | 'warehouse'
  | 'quality-trace'
  | 'vision-inspection'
  | 'root-cause'
  | 'quality-closed'

export type WorkflowData = {
  metadata: { name: string; runId: string; duration: string; status: string }
  nodes: FullWorkflowNode[]
  edges: FullWorkflowEdge[]
}

export const AGENT_OPTIONS: { value: AgentKey; label: string }[] = [
  { value: 'plan', label: '计划智能体' },
  { value: 'procurement', label: '采购智能体' },
  { value: 'warehouse', label: '仓储智能体' },
  { value: 'quality-trace', label: '质量追溯智能体' },
  { value: 'vision-inspection', label: '视觉质检智能体' },
  { value: 'root-cause', label: '根因分析智能体' },
  { value: 'quality-closed', label: '质量闭环管理智能体' },
]

export const WORKFLOW_MAP: Record<AgentKey, WorkflowData> = {
  plan: {
    metadata: {
      name: '计划智能体',
      runId: 'RUN-20260728-001',
      duration: '3m 42s',
      status: '已完成',
    },
    nodes: [
      { id: 's1', title: '需求接收', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '产能测算', type: 'ai', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '排程生成', type: 'ai', x: 40, y: 200, status: 'done' },
      { id: 's4', title: '异常校验', type: 'static', x: 40, y: 280, status: 'done' },
      { id: 's5', title: '下发工单', type: 'static', x: 40, y: 360, status: 'done' },
      { id: 'd1', title: '调用 ERP 接口', type: 'ai', x: 240, y: 120, status: 'done' },
      { id: 'd2', title: '设备采集', type: 'ai', x: 440, y: 120, status: 'done' },
      { id: 'd3', title: '交期校验', type: 'branch', x: 240, y: 200, status: 'done' },
      { id: 'd4', title: '重排迭代 #1', type: 'loop', x: 440, y: 200, status: 'done' },
      { id: 'd5', title: '重排迭代 #2', type: 'loop', x: 640, y: 200, status: 'done' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's2', to: 'd1', type: 'dynamic' },
      { id: 'e6', from: 'd1', to: 'd2', type: 'dynamic' },
      { id: 'e7', from: 's3', to: 'd3', type: 'dynamic' },
      { id: 'e8', from: 'd3', to: 'd4', type: 'dynamic' },
      { id: 'e9', from: 'd4', to: 'd5', type: 'dynamic' },
      { id: 'e10', from: 'd5', to: 's4', type: 'dynamic' },
    ],
  },
  procurement: {
    metadata: {
      name: '采购智能体',
      runId: 'RUN-20260728-002',
      duration: '5m 18s',
      status: '运行中',
    },
    nodes: [
      { id: 's1', title: '需求汇总', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '询比价', type: 'ai', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '供应商筛选', type: 'ai', x: 40, y: 200, status: 'running' },
      { id: 's4', title: '合同生成', type: 'ai', x: 40, y: 280, status: 'pending' },
      { id: 's5', title: '入库对账', type: 'static', x: 40, y: 360, status: 'pending' },
      { id: 'd1', title: '多家比价', type: 'branch', x: 240, y: 120, status: 'done' },
      { id: 'd2', title: '替代物料询价', type: 'branch', x: 440, y: 120, status: 'done' },
      { id: 'd3', title: '延期预警重采', type: 'loop', x: 640, y: 200, status: 'pending' },
      { id: 'd4', title: '资质核验', type: 'ai', x: 240, y: 200, status: 'running' },
      { id: 'd5', title: '风险评估', type: 'ai', x: 440, y: 200, status: 'pending' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's2', to: 'd1', type: 'dynamic' },
      { id: 'e6', from: 's2', to: 'd2', type: 'dynamic' },
      { id: 'e7', from: 'd1', to: 's3', type: 'dynamic' },
      { id: 'e8', from: 'd2', to: 's3', type: 'dynamic' },
      { id: 'e9', from: 's3', to: 'd4', type: 'dynamic' },
      { id: 'e10', from: 'd4', to: 'd5', type: 'dynamic' },
      { id: 'e11', from: 's4', to: 'd3', type: 'dynamic' },
      { id: 'e12', from: 'd3', to: 's2', type: 'dynamic' },
    ],
  },
  warehouse: {
    metadata: {
      name: '仓储智能体',
      runId: 'RUN-20260728-003',
      duration: '2m 30s',
      status: '运行中',
    },
    nodes: [
      { id: 's1', title: '入库质检', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '上架分配', type: 'ai', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '库存盘点', type: 'ai', x: 40, y: 200, status: 'running' },
      { id: 's4', title: '出库拣货', type: 'ai', x: 40, y: 280, status: 'pending' },
      { id: 's5', title: '库位预警', type: 'ai', x: 40, y: 360, status: 'pending' },
      { id: 'd1', title: '智能调拨', type: 'ai', x: 240, y: 200, status: 'running' },
      { id: 'd2', title: '临期物料转移', type: 'branch', x: 440, y: 200, status: 'pending' },
      { id: 'd3', title: '呆滞料分析', type: 'ai', x: 640, y: 280, status: 'pending' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's3', to: 'd1', type: 'dynamic' },
      { id: 'e6', from: 'd1', to: 'd2', type: 'dynamic' },
      { id: 'e7', from: 'd2', to: 's4', type: 'dynamic' },
      { id: 'e8', from: 's4', to: 'd3', type: 'dynamic' },
      { id: 'e9', from: 'd3', to: 's5', type: 'dynamic' },
    ],
  },
  'quality-trace': {
    metadata: {
      name: '质量追溯智能体',
      runId: 'RUN-20260728-004',
      duration: '8m 05s',
      status: '已完成',
    },
    nodes: [
      { id: 's1', title: '原料入库质检', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '工序巡检', type: 'static', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '成品检测', type: 'static', x: 40, y: 200, status: 'done' },
      { id: 's4', title: '出库留样', type: 'static', x: 40, y: 280, status: 'done' },
      { id: 's5', title: '售后召回', type: 'branch', x: 40, y: 360, status: 'done' },
      { id: 'd1', title: 'MES 工序数据', type: 'ai', x: 240, y: 120, status: 'done' },
      { id: 'd2', title: '供应商质检', type: 'static', x: 240, y: 40, status: 'done' },
      { id: 'd3', title: '批次链溯源', type: 'ai', x: 440, y: 200, status: 'done' },
      { id: 'd4', title: '正向追溯', type: 'branch', x: 640, y: 160, status: 'done' },
      { id: 'd5', title: '反向追溯', type: 'branch', x: 640, y: 240, status: 'done' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's1', to: 'd2', type: 'dynamic' },
      { id: 'e6', from: 's2', to: 'd1', type: 'dynamic' },
      { id: 'e7', from: 'd1', to: 'd3', type: 'dynamic' },
      { id: 'e8', from: 'd2', to: 'd3', type: 'dynamic' },
      { id: 'e9', from: 'd3', to: 'd4', type: 'dynamic' },
      { id: 'e10', from: 'd3', to: 'd5', type: 'dynamic' },
    ],
  },
  'vision-inspection': {
    metadata: {
      name: '视觉质检智能体',
      runId: 'RUN-20260728-005',
      duration: '1m 20s',
      status: '运行中',
    },
    nodes: [
      { id: 's1', title: '图像采集', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: 'AI 检测', type: 'ai', x: 40, y: 120, status: 'running' },
      { id: 's3', title: '缺陷分类', type: 'ai', x: 40, y: 200, status: 'pending' },
      { id: 's4', title: '缺陷标注', type: 'ai', x: 40, y: 280, status: 'pending' },
      { id: 's5', title: '分级判定', type: 'static', x: 40, y: 360, status: 'pending' },
      { id: 'd1', title: '图像预处理', type: 'ai', x: 240, y: 40, status: 'done' },
      { id: 'd2', title: '外观检测', type: 'ai', x: 240, y: 120, status: 'running' },
      { id: 'd3', title: '尺寸检测', type: 'ai', x: 440, y: 120, status: 'pending' },
      { id: 'd4', title: '划痕检测', type: 'ai', x: 640, y: 120, status: 'pending' },
      { id: 'd5', title: '坐标计算', type: 'static', x: 440, y: 200, status: 'pending' },
      { id: 'd6', title: '图纸比对', type: 'static', x: 640, y: 200, status: 'pending' },
      { id: 'd7', title: '推送 MES', type: 'static', x: 640, y: 280, status: 'pending' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's1', to: 'd1', type: 'dynamic' },
      { id: 'e6', from: 'd1', to: 'd2', type: 'dynamic' },
      { id: 'e7', from: 'd2', to: 'd3', type: 'dynamic' },
      { id: 'e8', from: 'd3', to: 'd4', type: 'dynamic' },
      { id: 'e9', from: 's2', to: 'd5', type: 'dynamic' },
      { id: 'e10', from: 'd5', to: 'd6', type: 'dynamic' },
      { id: 'e11', from: 's4', to: 'd7', type: 'dynamic' },
    ],
  },
  'root-cause': {
    metadata: {
      name: '根因分析智能体',
      runId: 'RUN-20260728-006',
      duration: '6m 30s',
      status: '运行中',
    },
    nodes: [
      { id: 's1', title: '不良数据接入', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '多维数据聚合', type: 'ai', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '关联度计算', type: 'ai', x: 40, y: 200, status: 'running' },
      { id: 's4', title: '根因排序', type: 'ai', x: 40, y: 280, status: 'pending' },
      { id: 's5', title: '验证模拟', type: 'ai', x: 40, y: 360, status: 'pending' },
      { id: 's6', title: '分析报告', type: 'static', x: 40, y: 440, status: 'pending' },
      { id: 'd1', title: '设备参数', type: 'static', x: 240, y: 120, status: 'done' },
      { id: 'd2', title: '物料批次', type: 'static', x: 440, y: 120, status: 'done' },
      { id: 'd3', title: '工艺记录', type: 'static', x: 640, y: 120, status: 'done' },
      { id: 'd4', title: '迭代 #1', type: 'loop', x: 240, y: 200, status: 'done' },
      { id: 'd5', title: '迭代 #2', type: 'loop', x: 440, y: 200, status: 'running' },
      { id: 'd6', title: '迭代 #3', type: 'loop', x: 640, y: 200, status: 'pending' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's5', to: 's6' },
      { id: 'e6', from: 's2', to: 'd1', type: 'dynamic' },
      { id: 'e7', from: 's2', to: 'd2', type: 'dynamic' },
      { id: 'e8', from: 's2', to: 'd3', type: 'dynamic' },
      { id: 'e9', from: 'd1', to: 's3', type: 'dynamic' },
      { id: 'e10', from: 'd2', to: 's3', type: 'dynamic' },
      { id: 'e11', from: 'd3', to: 's3', type: 'dynamic' },
      { id: 'e12', from: 's3', to: 'd4', type: 'dynamic' },
      { id: 'e13', from: 'd4', to: 'd5', type: 'dynamic' },
      { id: 'e14', from: 'd5', to: 'd6', type: 'dynamic' },
      { id: 'e15', from: 'd6', to: 's4', type: 'dynamic' },
    ],
  },
  'quality-closed': {
    metadata: {
      name: '质量闭环管理智能体',
      runId: 'RUN-20260728-007',
      duration: '4m 10s',
      status: '运行中',
    },
    nodes: [
      { id: 's1', title: '不良登记', type: 'static', x: 40, y: 40, status: 'done' },
      { id: 's2', title: '责任分配', type: 'ai', x: 40, y: 120, status: 'done' },
      { id: 's3', title: '临时隔离', type: 'static', x: 40, y: 200, status: 'done' },
      { id: 's4', title: '整改方案', type: 'ai', x: 40, y: 280, status: 'running' },
      { id: 's5', title: '整改执行', type: 'static', x: 40, y: 360, status: 'pending' },
      { id: 's6', title: '复检验证', type: 'static', x: 40, y: 440, status: 'pending' },
      { id: 's7', title: '关闭归档', type: 'static', x: 40, y: 520, status: 'pending' },
      { id: 'd1', title: '自动分级', type: 'branch', x: 240, y: 120, status: 'done' },
      { id: 'd2', title: '案例匹配', type: 'ai', x: 440, y: 280, status: 'running' },
      { id: 'd3', title: '逾期催办', type: 'loop', x: 640, y: 360, status: 'pending' },
      { id: 'd4', title: '多系统同步', type: 'ai', x: 640, y: 520, status: 'pending' },
    ],
    edges: [
      { id: 'e1', from: 's1', to: 's2' },
      { id: 'e2', from: 's2', to: 's3' },
      { id: 'e3', from: 's3', to: 's4' },
      { id: 'e4', from: 's4', to: 's5' },
      { id: 'e5', from: 's5', to: 's6' },
      { id: 'e6', from: 's6', to: 's7' },
      { id: 'e7', from: 's2', to: 'd1', type: 'dynamic' },
      { id: 'e8', from: 'd1', to: 's3', type: 'dynamic' },
      { id: 'e9', from: 's4', to: 'd2', type: 'dynamic' },
      { id: 'e10', from: 'd2', to: 's5', type: 'dynamic' },
      { id: 'e11', from: 's5', to: 'd3', type: 'dynamic' },
      { id: 'e12', from: 'd3', to: 's6', type: 'dynamic' },
      { id: 'e13', from: 's7', to: 'd4', type: 'dynamic' },
    ],
  },
}
