<script setup lang="ts">
import { FileText, Download, Calendar, Zap, Clock, BarChart3 } from 'lucide-vue-next'
import { Panel } from '@/components/ui-kit'
import { FP_REPORTS } from '@/lib/mock-extended'

const rp = FP_REPORTS

const kpis = [
  { label: '本月报告', value: rp.monthly, color: 'text-molybdenum', icon: Calendar },
  { label: '自动生成', value: rp.autoGenerated, color: 'text-patina', icon: Zap },
  { label: '平均生成', value: rp.avgGenTime, unit: 's', color: 'text-coolant', icon: Clock },
  { label: '下载次数', value: rp.downloads, color: 'text-sulfur', icon: Download },
]

const reportTypes = [
  { name: '日报', desc: '当日故障与处置摘要', icon: FileText },
  { name: '周报', desc: '周度趋势与风险复盘', icon: BarChart3 },
  { name: '月报', desc: '月度 KPI 与改善建议', icon: Calendar },
  { name: '专项', desc: '设备 / 故障专题分析', icon: Zap },
]

function typeBadge(type: string) {
  if (type === '日报') return 'bg-molybdenum/15 text-molybdenum border-molybdenum/40'
  if (type === '周报') return 'bg-coolant/15 text-coolant border-coolant/40'
  if (type === '月报') return 'bg-patina/15 text-patina border-patina/40'
  return 'bg-sulfur/15 text-sulfur border-sulfur/40'
}

const btnPrimary =
  'inline-flex items-center h-7 px-2.5 text-xs rounded bg-iron text-background hover:bg-iron/90 transition-colors'
const btnGhost =
  'inline-flex items-center !py-1 !px-2 h-auto text-xs rounded hover:bg-surface/60 transition-colors'
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-xl font-semibold">故障报告中心</h1>
        <p class="text-sm text-muted-foreground mt-1">日 / 周 / 月报自动生成 · 专项按需出</p>
      </div>
      <button :class="btnPrimary"><FileText class="size-3.5 mr-1" />生成报告</button>
    </div>

    <div class="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <Panel v-for="s in kpis" :key="s.label" class-name="!p-3">
        <div class="flex items-center gap-1.5 text-[11px] text-muted-foreground">
          <component :is="s.icon" class="size-3" />{{ s.label }}
        </div>
        <div class="mt-1 flex items-baseline gap-1">
          <span :class="['data-num text-xl font-semibold', s.color]">{{ s.value }}</span>
          <span v-if="s.unit" class="text-xs text-muted-foreground">{{ s.unit }}</span>
        </div>
      </Panel>
    </div>

    <div class="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <div
        v-for="t in reportTypes"
        :key="t.name"
        class="panel-surface rounded border border-border-hairline p-3 cursor-pointer hover:border-molybdenum/40 transition-colors"
      >
        <div class="flex items-center gap-2 mb-1">
          <component :is="t.icon" class="size-4 text-molybdenum" />
          <span class="text-xs font-medium">{{ t.name }}</span>
        </div>
        <p class="text-[11px] text-muted-foreground">{{ t.desc }}</p>
      </div>
    </div>

    <Panel title="报告列表">
      <table class="w-full text-xs">
        <thead>
          <tr class="border-b border-border-hairline text-muted-foreground">
            <th class="text-left py-2 font-medium">报告名称</th>
            <th class="text-left py-2 font-medium">类型</th>
            <th class="text-left py-2 font-medium">生成时间</th>
            <th class="text-left py-2 font-medium">页数</th>
            <th class="text-left py-2 font-medium">状态</th>
            <th class="text-right py-2 font-medium">操作</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="r in rp.reportsList"
            :key="r.id"
            class="border-b border-border-hairline/50 hover:bg-surface/50"
          >
            <td class="py-2.5 font-medium">{{ r.name }}</td>
            <td class="py-2.5">
              <span
                :class="[
                  'inline-flex items-center rounded border px-1.5 py-0.5 text-[10px]',
                  typeBadge(r.type),
                ]"
              >
                {{ r.type }}
              </span>
            </td>
            <td class="py-2.5 text-muted-foreground">{{ r.generated }}</td>
            <td class="py-2.5 data-num">{{ r.pages }}</td>
            <td class="py-2.5">
              <span
                class="inline-flex items-center rounded border px-1.5 py-0.5 text-[10px] bg-patina/15 text-patina border-patina/40"
              >
                {{ r.status }}
              </span>
            </td>
            <td class="py-2.5 text-right">
              <button :class="btnGhost"><Download class="size-3 mr-1" />下载</button>
            </td>
          </tr>
        </tbody>
      </table>
    </Panel>
  </div>
</template>
